(in-package :cl-rtmidi)

(include "stdbool.h")
(include "sys/stat.h")
(include "fcntl.h")
(include "stdio.h")
(include "errno.h")
(include "fcntl.h")
(include "stdlib.h")
(include "unistd.h")
(include "string.h")
(include "stdarg.h")
(include "sys/ioctl.h")
(include "asm-generic/termbits.h")

(constant (cbaud "CBAUD"))
(constant (tcgets2 "TCGETS2"))
(constant (tcsets2 "TCSETS2"))
(constant (bother "BOTHER"))
(constant (o-rdwr "O_RDWR"))
(constant (o-rdonly "O_RDONLY"))
(constant (o-wronly "O_WRONLY"))
(constant (o-noctty "O_NOCTTY"))

(cstruct termios2 "struct termios2"
	 (c-iflag "c_iflag" :type :uint)
	 (c-oflag "c_oflag" :type :uint)
	 (c-cflag "c_cflag" :type :uint)
	 (c-lflag "c_lflag" :type :uint)
	 (c-line "c_line" :type :uint)
	 (c-ispeed "c_ispeed" :type :uint)
	 (c-ospeed "c_ospeed" :type :uint))

;; (include "termios.h")
(constant (tciflush "TCIFLUSH"))
(constant (tcoflush "TCOFLUSH"))
